// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDo.Data;

namespace ToDo.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDo.Data.Models.Do", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("DoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoId")
                        .HasColumnName("DoId1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Done")
                        .HasColumnType("datetime2");

                    b.Property<string>("Executors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fact")
                        .HasColumnType("int");

                    b.Property<int>("Plan")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoId");

                    b.ToTable("ToDoes");
                });

            modelBuilder.Entity("ToDo.Data.Models.Do", b =>
                {
                    b.HasOne("ToDo.Data.Models.Do", null)
                        .WithMany("SubTasks")
                        .HasForeignKey("DoId");

                    b.HasOne("ToDo.Data.Models.Do", null)
                        .WithOne()
                        .HasForeignKey("ToDo.Data.Models.Do", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
